# Generated by Django 5.1.7 on 2025-04-24 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0002_initial_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="subrabble",
            name="community",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rabble.community",
            ),
            preserve_default=False,
        ),
    ]
