# Generated by Django 5.1.7 on 2025-04-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0003_subrabble_community"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
